version: "3.8"

services:
  haproxy:
    image: haproxy:3.2-alpine
    container_name: haproxy-proxy
    restart: unless-stopped
    network_mode: host
    volumes:
    - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    command: haproxy -f /usr/local/etc/haproxy/haproxy.cfg
